### ISSUE TITLE
User Story #1 - List of all Products

### ISSUE THREAD

**Issue by Kheirah** [Kheirah/backend-update-and-delete-demo#1]
## Value Proposition

**As a** ... (User, Author, logged in User...)  
**I want to** ... (describe the goal)  
**so that** ... (describe the reason)  
​

## Description

... (Wireframe, scribble, design or text)
​

## Acceptance Criteria

- [ ] Describe every scenarios in detail
- [ ] e.g. all inputs are required, show warning if empty.
- [ ] ...
      ​

## Tasks

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...
      ​

## Complexity

XXL
